name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Git repository
      uses: actions/checkout@v2

    - name: Cache LaTeX packages
      uses: actions/cache@v2
      with:
        path: |
          /usr/local/texlive
          ~/.texlive
        key: ${{ runner.os }}-texlive-${{ hashFiles('**/*.tex') }}
        restore-keys: |
          ${{ runner.os }}-texlive-

    - name: Compile LaTeX document (skills version)
      uses: xu-cheng/latex-action@v2
      with:
        root_file: main.tex
        pre_compile: |
          echo "\def\SkillVersion{}" > flag.tex
        post_compile: |
          mv main.pdf resume_skills.pdf

    - name: Compile LaTeX document (EA version)
      uses: xu-cheng/latex-action@v2
      with:
        root_file: main.tex
        pre_compile: |
          echo "\def\EAVersion{}" > flag.tex
        post_compile: |
          mv main.pdf resume_ea.pdf

    # Add steps to upload the PDFs as artifacts or commit back to the repository here
